### ISSUE TITLE
Kubernetes小记-基本概念和术语 — 苏耀东的博客

### ISSUE THREAD

**Issue by autume** [autume/autume.github.io#4]
https://suyaodong.top/2020/06/01/Kubernetes%E5%B0%8F%E8%AE%B0-%E5%9F%BA%E6%9C%AC%E6%A6%82%E5%BF%B5%E5%92%8C%E6%9C%AF%E8%AF%AD/ 

 Kubernetes基本概念

**Comment by jancee** [comment]
点个赞
